const F = (n) => `/images/flower_${n}.jpg`;

const categories = [
  {
    _id: 'cat_roses',
    name: { uz: 'Premium Atirgullar', ru: 'Премиум Розы', en: 'Premium Roses' },
    slug: 'premium-roses',
    description: { uz: 'Har qanday tadbir uchun hashamatli atirgullar', ru: 'Роскошные розы на любой случай', en: 'Luxury rose arrangements for every occasion' },
    image: F(1),
  },
  {
    _id: 'cat_seasonal',
    name: { uz: 'Mavsumiy Gullar', ru: 'Сезонные Цветы', en: 'Seasonal Blooms' },
    slug: 'seasonal-blooms',
    description: { uz: 'Eng yaxshi paytda yangi mavsumiy gullar', ru: 'Свежие сезонные цветы в лучший период', en: 'Fresh seasonal flowers at their peak' },
    image: F(5),
  },
  {
    _id: 'cat_wedding',
    name: { uz: 'To\'y Kolleksiyalari', ru: 'Свадебные Коллекции', en: 'Wedding Collections' },
    slug: 'wedding-collections',
    description: { uz: 'Nafis kelin guldastalari va to\'y dekoratsiyasi', ru: 'Элегантные свадебные букеты и декор', en: 'Elegant bridal bouquets and wedding decor' },
    image: F(4),
  },
  {
    _id: 'cat_gifts',
    name: { uz: 'Hashamatli Sovg\'alar', ru: 'Люкс Подарки', en: 'Luxury Gifts' },
    slug: 'luxury-gifts',
    description: { uz: 'Premium sovg\'a to\'plamlari', ru: 'Премиальные подарочные наборы', en: 'Premium gift sets and arrangements' },
    image: F(6),
  },
];

const products = [
  {
    _id: 'prod_1',
    name: { uz: 'Baxmal Tungi Atirgul', ru: 'Бархатная Полуночная Роза', en: 'Velvet Midnight Rose' },
    slug: 'velvet-midnight-rose',
    description: {
      uz: '24 ta qo\'lda tanlangan qora baxmal atirgullardan iborat nafis guldasta. Har bir atirgul mukammal gulbarg shakli uchun maxsus sharoitlarda yetishtirilgan.',
      ru: 'Изысканная композиция из 24 отборных черных бархатных роз, завернутых в матовую черную бумагу и перевязанных шелковой лентой цвета слоновой кости.',
      en: 'An exquisite arrangement of 24 hand-selected black velvet roses, wrapped in matte black tissue and finished with an ivory silk ribbon.',
    },
    price: 450000,
    discountPrice: 340000,
    discountPercentage: 24,
    category: 'cat_roses',
    images: [
      { url: F(1), alt: 'Velvet Midnight Rose' },
    ],
    stock: 15,
    tags: ['roses', 'premium', 'black', 'luxury'],
    isPremium: true,
    isNew: false,
    isGift: true,
    composition: '24 black velvet roses, eucalyptus, ivory ribbon',
    size: 'Large (50cm x 40cm)',
    rating: 4.8,
    reviewCount: 24,
  },
  {
    _id: 'prod_2',
    name: { uz: 'Oltin Soat Guldastasi', ru: 'Золотой Час', en: 'Golden Hour Bouquet' },
    slug: 'golden-hour-bouquet',
    description: {
      uz: 'Quyosh nuri bilan to\'ldirilgan oltin atirgullar, qaymoq rang pioniylar va quritilgan pampas o\'tlaridan iborat yorqin kompozitsiya.',
      ru: 'Сияющая композиция из золотистых роз, кремовых пионов и сушеных пампасных трав. Вдохновлена теплым свечением золотого часа.',
      en: 'A radiant arrangement of sun-kissed golden roses, cream peonies, and dried pampas grass.',
    },
    price: 320000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_roses',
    images: [
      { url: F(2), alt: 'Golden Hour Bouquet' },
    ],
    stock: 20,
    tags: ['roses', 'peonies', 'golden', 'premium'],
    isPremium: true,
    isNew: true,
    isGift: true,
    composition: '12 golden roses, 5 cream peonies, pampas grass',
    size: 'Medium (40cm x 30cm)',
    rating: 4.9,
    reviewCount: 18,
  },
  {
    _id: 'prod_3',
    name: { uz: 'Qizil Muhabbat', ru: 'Багровая Страсть', en: 'Crimson Affair' },
    slug: 'crimson-affair',
    description: {
      uz: 'To\'q bordo atirgullar quritilgan lavanda va qora ko\'katlar bilan uyg\'unlashgan dramatik, romantik kompozitsiya.',
      ru: 'Глубокие бордовые розы в паре с сушеной лавандой и черной зеленью — драматичная романтическая композиция.',
      en: 'Deep burgundy roses paired with dried lavender and black foliage in a dramatic, romantic arrangement.',
    },
    price: 280000,
    discountPrice: 220000,
    discountPercentage: 21,
    category: 'cat_roses',
    images: [
      { url: F(3), alt: 'Crimson Affair Bouquet' },
    ],
    stock: 12,
    tags: ['roses', 'burgundy', 'romantic', 'premium'],
    isPremium: true,
    isNew: false,
    isGift: true,
    composition: '18 burgundy roses, dried lavender, black foliage',
    size: 'Medium (40cm x 35cm)',
    rating: 4.7,
    reviewCount: 31,
  },
  {
    _id: 'prod_4',
    name: { uz: 'Oppoq Orzu', ru: 'Слоновая Кость', en: 'Ivory Dream' },
    slug: 'ivory-dream',
    description: {
      uz: 'Kelinnikiga mos fil suyagi bog\' atirgullari, oq ranunkulus va kumush bruniyadan iborat nozik guldasta.',
      ru: 'Эфирный свадебный букет из кремовых роз, белых ранункулюсов и серебристой брунии.',
      en: 'An ethereal bridal bouquet of ivory garden roses, white ranunculus, and silver brunia.',
    },
    price: 520000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_wedding',
    images: [
      { url: F(4), alt: 'Ivory Dream Bouquet' },
    ],
    stock: 8,
    tags: ['bridal', 'ivory', 'white', 'wedding', 'premium'],
    isPremium: true,
    isNew: false,
    isGift: false,
    composition: '12 ivory garden roses, 8 white ranunculus, silver brunia',
    size: 'Large (45cm x 35cm)',
    rating: 5.0,
    reviewCount: 15,
  },
  {
    _id: 'prod_5',
    name: { uz: 'Yovvoyi Yaylov', ru: 'Луговое Ассорти', en: 'Wild Meadow Mix' },
    slug: 'wild-meadow-mix',
    description: {
      uz: 'Yumshoq pastel ranglardagi mavsumiy yovvoyi gullarning jozibali aralashmasi.',
      ru: 'Беззаботная смесь сезонных полевых цветов в нежных пастельных тонах.',
      en: 'A carefree blend of seasonal wildflowers in soft pastels.',
    },
    price: 180000,
    discountPrice: 150000,
    discountPercentage: 17,
    category: 'cat_seasonal',
    images: [
      { url: F(5), alt: 'Wild Meadow Mix' },
    ],
    stock: 30,
    tags: ['wildflowers', 'pastel', 'seasonal', 'bohemian'],
    isPremium: false,
    isNew: true,
    isGift: true,
    composition: 'Seasonal wildflowers, dried grasses, limonium',
    size: 'Small (30cm x 25cm)',
    rating: 4.5,
    reviewCount: 42,
  },
  {
    _id: 'prod_6',
    name: { uz: 'Qirollik Orxidey', ru: 'Королевский Каскад Орхидей', en: 'Royal Orchid Cascade' },
    slug: 'royal-orchid-cascade',
    description: {
      uz: 'To\'q binafsha va oq rangdagi noyob phalaenopsis orxideylaridan iborat kaskad kompozitsiya.',
      ru: 'Каскадная композиция из редких фаленопсисов глубокого пурпурного и белого цвета.',
      en: 'A cascading arrangement of rare phalaenopsis orchids in deep purple and white.',
    },
    price: 680000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_gifts',
    images: [
      { url: F(6), alt: 'Royal Orchid Cascade' },
    ],
    stock: 5,
    tags: ['orchids', 'purple', 'premium', 'luxury', 'vase'],
    isPremium: true,
    isNew: false,
    isGift: true,
    composition: '7 phalaenopsis orchids, ceramic vase included',
    size: 'Extra Large (60cm x 25cm)',
    rating: 4.9,
    reviewCount: 11,
  },
  {
    _id: 'prod_7',
    name: { uz: 'Yozgi Kun', ru: 'Летнее Солнцестояние', en: 'Summer Solstice Posy' },
    slug: 'summer-solstice-posy',
    description: {
      uz: 'Yorqin kungaboqarlar, oltin xrizantemalar va terrakota chinnigullar tabiiy jut bilan bog\'langan.',
      ru: 'Яркие подсолнухи, золотые хризантемы и терракотовые гвоздики, перевязанные натуральной джутовой веревкой.',
      en: 'Bright sunflowers, golden chrysanthemums, and terracotta carnations tied with natural jute.',
    },
    price: 150000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_seasonal',
    images: [
      { url: F(7), alt: 'Summer Solstice Posy' },
    ],
    stock: 25,
    tags: ['sunflowers', 'summer', 'seasonal', 'bright'],
    isPremium: false,
    isNew: false,
    isGift: true,
    composition: '5 sunflowers, chrysanthemums, carnations, jute wrap',
    size: 'Medium (35cm x 30cm)',
    rating: 4.3,
    reviewCount: 28,
  },
  {
    _id: 'prod_8',
    name: { uz: 'Oy Nurli Serenada', ru: 'Лунная Серенада', en: 'Moonlight Serenade' },
    slug: 'moonlight-serenade',
    description: {
      uz: 'Oq va qaymoq rangidagi gullar yarim oy shaklida joylashtirilgan. Oy gullari, oq zambaklar va kumush evkalipt.',
      ru: 'Белые и кремовые цветы в форме полумесяца. Лунные цветы, белые лилии и серебристый эвкалипт.',
      en: 'White and cream blooms arranged in a crescent silhouette featuring moonflowers and white lilies.',
    },
    price: 380000,
    discountPrice: 310000,
    discountPercentage: 18,
    category: 'cat_roses',
    images: [
      { url: F(8), alt: 'Moonlight Serenade' },
    ],
    stock: 10,
    tags: ['white', 'moonflower', 'lily', 'evening', 'premium'],
    isPremium: true,
    isNew: true,
    isGift: true,
    composition: 'Moonflowers, white lilies, silver eucalyptus',
    size: 'Large (50cm x 35cm)',
    rating: 4.7,
    reviewCount: 9,
  },
  {
    _id: 'prod_9',
    name: { uz: 'Pushti Pion Bog\'i', ru: 'Розовый Пионовый Сад', en: 'Blush Peony Garden' },
    slug: 'blush-peony-garden',
    description: {
      uz: 'Pushti pioniylar, ranunkulus va no\'xat gullaridan iborat hashamatli bog\'.',
      ru: 'Пышный сад из розовых пионов, лютиков и душистого горошка.',
      en: 'A lush garden of blush pink peonies, ranunculus, and sweet peas.',
    },
    price: 420000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_roses',
    images: [
      { url: F(4), alt: 'Blush Peony Garden' },
    ],
    stock: 7,
    tags: ['peonies', 'blush', 'pink', 'spring', 'premium'],
    isPremium: true,
    isNew: false,
    isGift: true,
    composition: '10 blush peonies, ranunculus, sweet peas, eucalyptus',
    size: 'Large (45cm x 40cm)',
    rating: 4.9,
    reviewCount: 36,
  },
  {
    _id: 'prod_10',
    name: { uz: 'Minimalist', ru: 'Минималист', en: 'The Minimalist' },
    slug: 'the-minimalist',
    description: {
      uz: 'Bitta mukammal kalla zambak sopol silindrda. Toza chiziqlar, salbiy bo\'shliq, me\'moriy go\'zallik.',
      ru: 'Один стебель идеальной каллы в минималистичном керамическом цилиндре. Чистые линии, архитектурная красота.',
      en: 'A single stem of a perfect calla lily in a minimalist ceramic cylinder. Clean lines, architectural beauty.',
    },
    price: 95000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_gifts',
    images: [
      { url: F(10), alt: 'The Minimalist' },
    ],
    stock: 50,
    tags: ['minimalist', 'calla lily', 'modern', 'small'],
    isPremium: false,
    isNew: true,
    isGift: false,
    composition: 'Single calla lily with ceramic cylinder vase',
    size: 'Small (25cm x 10cm)',
    rating: 4.4,
    reviewCount: 53,
  },
  {
    _id: 'prod_11',
    name: { uz: 'Abadiy Sevgi', ru: 'Венок Вечной Любви', en: 'Eternal Love Wreath' },
    slug: 'eternal-love-wreath',
    description: {
      uz: 'Quritilgan atirgullardan yasalgan gulchambar mis halqada. Abadiy qolish uchun yaratilgan — cheksiz sevgining ramzi.',
      ru: 'Венок из консервированных роз на латунном кольце. Создан, чтобы длиться вечно — символ вечной любви.',
      en: 'A preserved rose wreath in deep burgundy and blush, mounted on a brass ring. Designed to last forever.',
    },
    price: 350000,
    discountPrice: 280000,
    discountPercentage: 20,
    category: 'cat_gifts',
    images: [
      { url: F(1), alt: 'Eternal Love Wreath' },
    ],
    stock: 10,
    tags: ['wreath', 'preserved', 'love', 'eternal', 'luxury'],
    isPremium: true,
    isNew: false,
    isGift: true,
    composition: 'Preserved roses on brass ring, 30cm diameter',
    size: 'Medium (30cm diameter)',
    rating: 4.6,
    reviewCount: 19,
  },
  {
    _id: 'prod_12',
    name: { uz: 'Bahor Uyg\'onishi', ru: 'Весеннее Пробуждение', en: 'Spring Awakening' },
    slug: 'spring-awakening',
    description: {
      uz: 'Lolalar, sümbüller va nargislarning yumshoq sariq, qaymoq va och yashil ranglardagi bahor kompozitsiyasi.',
      ru: 'Праздник весны с тюльпанами, гиацинтами и нарциссами в мягких желтых, кремовых и бледно-зеленых тонах.',
      en: 'A celebration of spring with tulips, hyacinths, and daffodils in soft yellows, creams, and pale greens.',
    },
    price: 220000,
    discountPrice: null,
    discountPercentage: null,
    category: 'cat_seasonal',
    images: [
      { url: F(2), alt: 'Spring Awakening' },
    ],
    stock: 18,
    tags: ['spring', 'tulips', 'hyacinth', 'seasonal'],
    isPremium: false,
    isNew: false,
    isGift: true,
    composition: 'Tulips, hyacinths, daffodils in moss-lined basket',
    size: 'Medium (35cm x 30cm)',
    rating: 4.5,
    reviewCount: 22,
  },
];

export { categories, products };
